import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-8">
      <Card>
        <CardHeader>
          <CardTitle className="font-bold text-3xl">Terms of Service</CardTitle>
          <p className="text-muted-foreground">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </CardHeader>
        <CardContent className="space-y-6">
          <section>
            <h2 className="mb-4 font-semibold text-2xl">
              1. Acceptance of Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing and using YouTube to Blog ("the Service"), you accept
              and agree to be bound by the terms and provision of this
              agreement. If you do not agree to abide by the above, please do
              not use this service.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">
              2. Description of Service
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              YouTube to Blog is a web application that converts YouTube video
              content into blog post format. The service uses artificial
              intelligence to analyze video content and generate written blog
              posts based on the video's content, transcript, and metadata.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">3. User Accounts</h2>
            <div className="space-y-3 text-muted-foreground">
              <p>To use our service, you must:</p>
              <ul className="ml-4 list-inside list-disc space-y-2">
                <li>
                  Provide accurate and complete information when creating an
                  account
                </li>
                <li>Maintain the security of your password and account</li>
                <li>
                  Accept responsibility for all activities under your account
                </li>
                <li>
                  Notify us immediately of any unauthorized use of your account
                </li>
              </ul>
            </div>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">4. Acceptable Use</h2>
            <div className="space-y-3 text-muted-foreground">
              <p>You agree not to use the service to:</p>
              <ul className="ml-4 list-inside list-disc space-y-2">
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe on intellectual property rights of others</li>
                <li>
                  Upload or process content that is illegal, harmful, or
                  offensive
                </li>
                <li>Attempt to gain unauthorized access to our systems</li>
                <li>
                  Use the service for commercial purposes without permission
                </li>
                <li>
                  Distribute malware or engage in any malicious activities
                </li>
              </ul>
            </div>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">
              5. Content and Intellectual Property
            </h2>
            <div className="space-y-3 text-muted-foreground">
              <p>
                You retain ownership of any content you submit to our service.
                By using our service, you grant us a limited license to process
                your content solely for the purpose of providing the service.
              </p>
              <p>
                The generated blog content is based on publicly available
                YouTube content. You are responsible for ensuring you have the
                right to use and publish any content generated by our service.
              </p>
            </div>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">
              6. Privacy and Data Protection
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Your privacy is important to us. Please review our Privacy Policy,
              which also governs your use of the service, to understand our
              practices.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">
              7. Service Availability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We strive to maintain high service availability but do not
              guarantee uninterrupted access. We may temporarily suspend the
              service for maintenance, updates, or other operational reasons.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">
              8. Limitation of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, YouTube to Blog shall not
              be liable for any indirect, incidental, special, consequential, or
              punitive damages, including without limitation, loss of profits,
              data, use, goodwill, or other intangible losses.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">9. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may terminate or suspend your account and access to the service
              immediately, without prior notice, for any reason, including if
              you breach these Terms of Service.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">
              10. Changes to Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to modify these terms at any time. We will
              notify users of any material changes via email or through the
              service. Your continued use of the service after such
              modifications constitutes acceptance of the updated terms.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="mb-4 font-semibold text-2xl">
              11. Contact Information
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms of Service, please
              contact us through our support channels.
            </p>
          </section>
        </CardContent>
      </Card>
    </div>
  );
}
